// Generated by Wrangler by running `wrangler types`

interface Env {
	MyActor: DurableObjectNamespace<import("./sample/index").MyActor>;
	MyActor2: DurableObjectNamespace<import("./sample/index").MyActor2>;
}
